### ISSUE TITLE
Generic gmail storage was able to be connected to a Sid job. Is this intended?

### ISSUE THREAD

**Issue by mreekie** [hmdc/Sid-feedback-bugs-enhancements-NOCODE#3]
Feedback from CSS team.
User was able to connect a generic gmail account or customer gmail domain to their job.
This is not supposed to be allowed is it?
I thought we only allow g.harvard.edu accounts.

**Comment by mallove** [comment]
Sid has always supported both gmail and g.harvard.edu accounts.

**Comment by mreekie** [comment]
I thought on this one, due to Level 3 security requirements we only were able to use g.harvard.edu?

**Comment by mreekie** [comment]
For now the feedback is that Liz/Sid would asked to leave the ability to connect to a personal account enabled.

**Comment by mreekie** [comment]
See also:
Users not at Harvard who need access to google drive? #286
